-- Supabase Setup Script

-- 1. Create Tables
CREATE TABLE public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  name text,
  email text,
  xp_total integer default 0,
  level integer default 1,
  streak integer default 0,
  last_study_date text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE public.subjects (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE public.topics (
  id bigint generated by default as identity primary key,
  subject_id bigint references public.subjects(id) on delete cascade not null,
  name text not null,
  mastery_level integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE public.missions (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  title text not null,
  type text,
  difficulty text,
  duration integer default 30,
  xp integer default 0,
  date text,
  subject_id bigint references public.subjects(id) on delete set null,
  completed boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE public.sessions (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  mission_id bigint references public.missions(id) on delete set null,
  duration integer default 0,
  xp_earned integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE public.user_achievements (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  achievement_id integer not null,
  unlocked_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Auth Trigger
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, name)
  VALUES (new.id, new.email, new.raw_user_meta_data->>'name');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 3. Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.topics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.missions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_achievements ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
CREATE POLICY "Users can create their own profile." ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can view their own profile." ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Subjects Policies
CREATE POLICY "Users can manage their subjects." ON public.subjects FOR ALL USING (auth.uid() = user_id);

-- Topics Policies
CREATE POLICY "Users can manage topics via subject" ON public.topics FOR ALL USING (
  EXISTS (SELECT 1 FROM public.subjects s WHERE s.id = subject_id AND s.user_id = auth.uid())
);

-- Missions Policies
CREATE POLICY "Users can manage their missions." ON public.missions FOR ALL USING (auth.uid() = user_id);

-- Sessions Policies
CREATE POLICY "Users can manage their sessions." ON public.sessions FOR ALL USING (auth.uid() = user_id);

-- Achievements Policies
CREATE POLICY "Users can manage their achievements." ON public.user_achievements FOR ALL USING (auth.uid() = user_id);
